{% set version = "1.1.2" %}

package:
  name: sphinxcontrib-shellcheck
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/s/sphinxcontrib-shellcheck/sphinxcontrib-shellcheck-{{ version }}.zip
  sha256: 475a3ae12a1cfc1bc26cff57f0dd15561213818e3b470b3eacc4bb8be7b129c0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - decorator
    - docutils
    - python >={{ python_min }}
    - six
    - sphinx
    # from _check_version in sphinxcontrib/shellcheck.py
    - shellcheck >=0.4.4

test:
  imports:
    - sphinxcontrib.shellcheck
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pmacosta/sphinxcontrib-shellcheck
  summary: Sphinx extension to lint shell code blocks
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/sphinx
    - bollwyvl
